# Generated by Django 2.2.12 on 2020-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
                ('author_age', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='blog',
            constraint=models.CheckConstraint(check=models.Q(author_age__gte=18), name='age_gte_18'),
        ),
    ]
