# Generated by Django 2.2.12 on 2020-06-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200622_0714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casablanca',
            new_name='Weather',
        ),
    ]
